#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Builds brand/syvt-og.svg, the Open Graph artwork for the game.

Usage:  python brand/make-wordmark.py
Needs, for rendering only and never at runtime:  pip install fonttools brotli
(brotli is what lets fontTools open the woff2.)

The wordmark is emitted as Manrope ExtraBold OUTLINES rather than <text>, so
the artwork renders identically anywhere and needs no font resolved at render
time - which is also what lets SYVT/make-icons.mjs rasterise it with sharp.

That conversion is one-way, so this script is the only way back: if the game
is renamed again, change WORD below and re-run, then re-run make-icons.mjs to
refresh og.png. The mark's own geometry is copied from brand/syvt-mark.svg -
the clip polygons live in the group's local space, so they carry over
unchanged whatever the scale.
"""
import io
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Transform

WORD = "SYVT"
FONT = "SYVT/manrope.woff2"
OUT = "brand/syvt-og.svg"

W, H = 1200, 630
INK = "#05100f"
STEM, WRONG, RIGHT = "#e6f6f4", "#fb7185", "#2dd4bf"
WORD_TOP, WORD_BOT = "#ffffff", "#a9e7e1"   # matches .brand-name's gradient

WEIGHT = 800           # Manrope's wght axis, same as .brand-name
TRACKING = 0.22        # em, same as .brand-name letter-spacing
CAP_PX = 116           # cap height of the wordmark on the 1200x630 canvas
MARK_PX = 300          # the mark's drawn height
GAP = 78               # space between mark and wordmark

font = instancer.instantiateVariableFont(TTFont(FONT), {"wght": WEIGHT})
upem = font["head"].unitsPerEm
cmap = font.getBestCmap()
glyphs = font.getGlyphSet()
cap = font["OS/2"].sCapHeight

k = CAP_PX / cap       # px per font unit, so the cap height lands on CAP_PX

parts, pen_x = [], 0.0
for ch in WORD:
    glyph = glyphs[cmap[ord(ch)]]
    # y-flip: font units go up, SVG goes down. Baseline sits at y = 0.
    pen = SVGPathPen(glyphs)
    glyph.draw(TransformPen(pen, Transform(k, 0, 0, -k, pen_x, 0)))
    if pen.getCommands():
        parts.append(pen.getCommands())
    pen_x += glyph.width * k + TRACKING * upem * k

word_w = pen_x - TRACKING * upem * k    # drop the trailing track
total_w = MARK_PX + GAP + word_w
x0 = (W - total_w) / 2

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}">
  <title>{WORD}</title>
  <!-- Open Graph artwork, {W}x{H}. GENERATED by brand/make-wordmark.py - edit
       that, not this. The mark is the same geometry and the same bisector
       knockouts as brand/syvt-mark.svg. The wordmark is Manrope wght {WEIGHT}
       at {TRACKING}em tracking, converted to outlines, so nothing here needs a
       font at render time. -->
  <defs>
    <clipPath id="svL"><polygon points="60,73 60,600 -940,600 -940,-441.618"/></clipPath>
    <clipPath id="svR"><polygon points="60,73 60,600 1060,600 1060,-441.618"/></clipPath>
    <linearGradient id="wm" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="{WORD_TOP}"/>
      <stop offset="1" stop-color="{WORD_BOT}"/>
    </linearGradient>
  </defs>
  <rect width="{W}" height="{H}" fill="{INK}"/>
  <g transform="translate({x0:.2f} {(H - MARK_PX) / 2:.2f}) scale({MARK_PX / 120.0:.5f})">
    <g fill="none" stroke-width="13" stroke-linecap="round" stroke-linejoin="round">
      <path d="M60 17 L60 73"   stroke="{STEM}"/>
      <path d="M60 73 L18 103"  stroke="{WRONG}" clip-path="url(#svL)"/>
      <path d="M60 73 L102 103" stroke="{RIGHT}" clip-path="url(#svR)"/>
    </g>
  </g>
  <g transform="translate({x0 + MARK_PX + GAP:.2f} {H / 2 + CAP_PX / 2:.2f})" fill="url(#wm)">
    <path d="{' '.join(parts)}"/>
  </g>
</svg>
'''

io.open(OUT, "w", encoding="utf-8", newline="\n").write(svg)
print('%s  "%s"  wordmark %.1fpx wide  lockup %.1fpx' % (OUT, WORD, word_w, total_w))
